all:
  children:
    mac_local:
      hosts:
        localhost:
          ansible_connection: local
    jarvis_core:
      hosts:
        hostinger-kvm2:
          ansible_host: 187.77.242.208
          ansible_user: root
          ansible_ssh_private_key_file: /Users/diego/.ssh/hostinger
    oracle_staging:
      hosts:
        oracle-prod:
          ansible_host: 167.234.228.71
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/diego/.ssh/id_ed25519
        oracle-test:
          ansible_host: 129.148.17.85
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/diego/dev/GitHub/vps-oracle/ssh/ssh-key-2026-03-10.key
