#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
REMOTE_HOST="${RUPTUR_REMOTE_HOST:-hostinger-kvm2}"
REMOTE_DIR="${RUPTUR_LANGFUSE_REMOTE_DIR:-/opt/ruptur/runtime/langfuse}"
REMOTE_ENV="$REMOTE_DIR/.env"
REMOTE_COMPOSE="$REMOTE_DIR/docker-compose.yml"
LOCAL_TEMPLATE="$ROOT_DIR/adapters/ruptur-forge/templates/runtime/langfuse.compose.yml"
PUBLIC_BASE_URL="${LANGFUSE_PUBLIC_BASE_URL:-http://187.77.242.208:3000}"
MINIO_BASE_URL="${LANGFUSE_MINIO_BASE_URL:-http://187.77.242.208:9090}"

ssh "$REMOTE_HOST" "mkdir -p '$REMOTE_DIR'"
scp "$LOCAL_TEMPLATE" "$REMOTE_HOST:$REMOTE_COMPOSE" >/dev/null
ssh "$REMOTE_HOST" "if [ ! -f '$REMOTE_ENV' ]; then
umask 077
POSTGRES_PASSWORD=\$(openssl rand -hex 16)
CLICKHOUSE_PASSWORD=\$(openssl rand -hex 16)
MINIO_SECRET=\$(openssl rand -hex 16)
REDIS_SECRET=\$(openssl rand -hex 16)
NEXTAUTH_SECRET_VALUE=\$(openssl rand -hex 24)
SALT_VALUE=\$(openssl rand -hex 16)
ENCRYPTION_KEY_VALUE=\$(openssl rand -hex 32)
INIT_PASSWORD=\$(openssl rand -base64 24 | tr -d '\n')
cat > '$REMOTE_ENV' <<EOF
NEXTAUTH_URL=$PUBLIC_BASE_URL
NEXTAUTH_SECRET=\${NEXTAUTH_SECRET_VALUE}
DATABASE_URL=postgresql://postgres:\${POSTGRES_PASSWORD}@postgres:5432/postgres
SALT=\${SALT_VALUE}
ENCRYPTION_KEY=\${ENCRYPTION_KEY_VALUE}
TELEMETRY_ENABLED=true
LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
CLICKHOUSE_DB=default
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=\${CLICKHOUSE_PASSWORD}
CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:\${CLICKHOUSE_PASSWORD}@clickhouse:9000
CLICKHOUSE_URL=http://clickhouse:8123
LANGFUSE_USE_AZURE_BLOB=false
LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse
LANGFUSE_S3_EVENT_UPLOAD_REGION=auto
LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=\${MINIO_SECRET}
LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://minio:9000
LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true
LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/
LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=langfuse
LANGFUSE_S3_MEDIA_UPLOAD_REGION=auto
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=\${LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY}
LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=$MINIO_BASE_URL
LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=true
LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=media/
LANGFUSE_S3_BATCH_EXPORT_ENABLED=false
LANGFUSE_S3_BATCH_EXPORT_BUCKET=langfuse
LANGFUSE_S3_BATCH_EXPORT_PREFIX=exports/
LANGFUSE_S3_BATCH_EXPORT_REGION=auto
LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=http://minio:9000
LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT=$MINIO_BASE_URL
LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=minio
LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=\${LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY}
LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE=true
REDIS_AUTH=\${REDIS_SECRET}
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_TLS_ENABLED=false
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=\${MINIO_SECRET}
POSTGRES_USER=postgres
POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
POSTGRES_DB=postgres
TZ=UTC
PGTZ=UTC
LANGFUSE_WEB_PORT=3000
LANGFUSE_MINIO_PORT=9090
LANGFUSE_INIT_USER_EMAIL=admin@ruptur.cloud
LANGFUSE_INIT_USER_NAME=Ruptur Admin
LANGFUSE_INIT_USER_PASSWORD=\${INIT_PASSWORD}
EOF
fi
sudo ufw allow 3000/tcp >/dev/null 2>&1 || true
sudo ufw allow 9090/tcp >/dev/null 2>&1 || true
cd '$REMOTE_DIR'
docker compose --env-file '$REMOTE_ENV' up -d
docker compose --env-file '$REMOTE_ENV' ps"
