shipyard_dirs_directories:
  - "{{ shipyard_base_dir }}"
  - "{{ shipyard_compose_dir }}"
  - "{{ shipyard_config_dir }}"
  - "{{ shipyard_data_dir }}"
  - "{{ shipyard_logs_dir }}"
  - "{{ shipyard_runtime_dir }}"
  - "{{ shipyard_backup_dir }}"
  - "{{ shipyard_config_dir }}/traefik"
  - "{{ shipyard_config_dir }}/traefik/dynamic"
  - "{{ shipyard_data_dir }}/traefik"
  - "{{ shipyard_data_dir }}/portainer"
  - "{{ shipyard_data_dir }}/postgres"
  - "{{ shipyard_data_dir }}/redis"
  - "{{ shipyard_data_dir }}/n8n"
  - "{{ shipyard_data_dir }}/minio"
  - "{{ shipyard_data_dir }}/jarvis"
  - "{{ shipyard_config_dir }}/jarvis"
  - "{{ shipyard_runtime_dir }}/jarvis"
  - "{{ shipyard_runtime_dir }}/state"

shipyard_dirs_ownerships:
  - path: "{{ shipyard_data_dir }}/n8n"
    owner: "1000"
    group: "1000"
    mode: "0755"
